model: o1
backend: genai
temperature: 0.0
system_prompt:  
reasoning: false
definitions_path: taxonomy_definitions_examples/definitions.txt
examples_path: taxonomy_definitions_examples/examples.txt
dataset_path: data/human_labelled
genai_project: ingka-map-services-dev
genai_location: europe-west1
ollama_host: http://localhost:11434